# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookhub < Formula
  desc "Tunnel webhooks captured at a stable WebhookHub URL down to your local server"
  homepage "https://webhookhub.dev"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v1.0.0/webhookhub_1.0.0_darwin_amd64.tar.gz"
      sha256 "fa28ab8ab20e5d0c886173ea6d77c764d8f4c1de23ff658a2dbcfd9a3a4e438a"

      define_method(:install) do
        bin.install "webhookhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v1.0.0/webhookhub_1.0.0_darwin_arm64.tar.gz"
      sha256 "8eada3ea1e93aa7e51cb0f8b5537052cddbc6f91f2c1ca9844e075dab64e1e38"

      define_method(:install) do
        bin.install "webhookhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v1.0.0/webhookhub_1.0.0_linux_amd64.tar.gz"
      sha256 "0daa4c5ed0dd2a6662281799db598e9800289720c131c13bdead5a6542855f1b"
      define_method(:install) do
        bin.install "webhookhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v1.0.0/webhookhub_1.0.0_linux_arm64.tar.gz"
      sha256 "a45c47dc8dd092ccf03601b482eae9b3edf7dabad16ebfdfc7dab93e12d5b674"
      define_method(:install) do
        bin.install "webhookhub"
      end
    end
  end

  test do
    system "#{bin}/webhookhub", "--version"
  end
end
