# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookhub < Formula
  desc "Tunnel webhooks captured at a stable WebhookHub URL down to your local server"
  homepage "https://webhookhub.dev"
  version "0.3.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v0.3.1-alpha/webhookhub_0.3.1-alpha_darwin_amd64.tar.gz"
      sha256 "04b06041b988fe0a43675b6a847be2c20255c517be818a9bebff3c475665f35a"

      define_method(:install) do
        bin.install "webhookhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v0.3.1-alpha/webhookhub_0.3.1-alpha_darwin_arm64.tar.gz"
      sha256 "06853cc2dcfd59cbb053e9e24cca123fbcf3aec17067cf7533eac182d93a9d92"

      define_method(:install) do
        bin.install "webhookhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v0.3.1-alpha/webhookhub_0.3.1-alpha_linux_amd64.tar.gz"
      sha256 "40ca85c449c59d39d5f3528ba2dd2ca5c590d2d9a46608e363b5ced46bc1efb6"
      define_method(:install) do
        bin.install "webhookhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shire-studio/webhookhub-cli/releases/download/v0.3.1-alpha/webhookhub_0.3.1-alpha_linux_arm64.tar.gz"
      sha256 "785860193b5ee7d4ab158d6844304201f849ad4b4a7957f89a89d631e0d1d1ea"
      define_method(:install) do
        bin.install "webhookhub"
      end
    end
  end

  test do
    system "#{bin}/webhookhub", "--version"
  end
end
